name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ✨ Setup .NET
        uses: actions/setup-dotnet@v4
      - name: 🚚 Restore
        run: dotnet restore src
      - name: 🛠️ Build
        run: dotnet build src --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test src --configuration Release --no-build